sudo: required
language: c++
services:
    - docker
env:
    global:
    matrix:
        - SCRIPT="build_clang6_Debug_none"
        - SCRIPT="build_clang6_Release_none"
        - SCRIPT="build_clang7_Debug_address"
        - SCRIPT="build_clang7_Debug_thread"
        - SCRIPT="build_clang7_Debug_undefined"
        - SCRIPT="build_clang7_Profile_none"
        - SCRIPT="build_clang7_Release_none"
        - SCRIPT="build_clang7_Relwithdebinfo_none"
        - SCRIPT="build_default-clang_Debug_none"
        - SCRIPT="build_gcc7_Debug_none"
        - SCRIPT="build_gcc7_Release_none"
        - SCRIPT="build_gcc8_Debug_address"
        - SCRIPT="build_gcc8_Debug_thread"
        - SCRIPT="build_gcc8_Debug_undefined"
        - SCRIPT="build_gcc8_Profile_none"
        - SCRIPT="build_gcc8_Release_none"
        - SCRIPT="build_gcc8_Relwithdebinfo_none"
        - SCRIPT="build_default-gcc_Debug_none"
        - SCRIPT="gnu_make"
        - SCRIPT="pic"

script:
    - docker build -t but-sdk --cache-from baszerr/but-sdk sdk/
    - >
        docker run
        --rm
        --cap-add=SYS_PTRACE
        --volume $(pwd):/mnt
        but-sdk
        /mnt/ci/"${SCRIPT}"
