#!/bin/bash
set -eu -o pipefail

APP_DIR=$(dirname "$(readlink -e "$0")")
cd "$APP_DIR"

IMG="but_sdk"
time docker build -t "$IMG" "sdk"

time docker run \
  -it \
  --rm \
  --cap-add=SYS_PTRACE \
  -u "$(id -u):$(id -g)" \
  -v "$PWD:/mnt" \
  -w "/mnt" \
  "$IMG" \
  "$@"
