#!/bin/bash
set -eu -o pipefail
app=$(basename "$0")
app_dir=$(dirname "$(readlink -e "$0")")

if [ $# -lt 1 ]
then
  echo "$app <sdk_name> [cmd [args..]]" >&2
  exit 2
fi
sdk=$1
shift 1

cd "$app_dir"

img="but_sdk_$sdk"
docker build -t "$img" "sdk/$sdk/"

docker run \
  -it \
  --rm \
  --cap-add=SYS_PTRACE \
  -u "$(id -u):$(id -g)" \
  -v "$PWD:/mnt" \
  -w "/mnt" \
  "$img" \
  "$@"
