if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
  if ("${CMAKE_CXX_COMPILER_VERSION}" MATCHES "^12\\.")
    include(cmake/flags/gcc12.cmake)
  endif()
  if ("${CMAKE_CXX_COMPILER_VERSION}" MATCHES "^14\\.")
    include(cmake/flags/gcc14.cmake)
  endif()
endif()
