#!/bin/bash
set -ex

if [ $# -ne 0 ]
then
  echo "$0: this script takes no arguments"
  exit 1
fi

APP_DIR=$(dirname "$(readlink -e "$0")")
SRC_DIR=$(readlink -e "$APP_DIR/..")

cd "$SRC_DIR/build/"
mkdir -p "gnu-make"
cd "$_"

TCC="-DCMAKE_TOOLCHAIN_FILE=$SRC_DIR/src/cmake/toolchains/gcc.cmake"

time cmake $TCC "-DCMAKE_BUILD_TYPE=Debug" -G "Unix Makefiles" "$SRC_DIR"
time make -j$(nproc) all
time ctest || ctest -V
