#!/bin/bash
set -eu -o pipefail
app=$(basename "$0")
app_dir=$(dirname "$(readlink -e "$0")")

if [ "$#" -ne 0 ]
then
  echo "$app: script takes no arguments" >&2
  exit 2
fi

export $BUT_GENERATOR="Unix Makefiles"
exec "$app_dir/build" "gcc" "Debug" "none"
