FROM debian:9.0

RUN apt-get update
RUN apt-get dist-upgrade -y

RUN apt-get install -y cmake
RUN apt-get install -y make ninja-build
RUN apt-get install -y googletest
RUN apt-get install -y libboost-all-dev
RUN apt-get install -y g++
RUN apt-get install -y clang llvm
