if("${SANITIZE}" STREQUAL "address")
  message(STATUS "enabling address sanitizer")
  add_compile_options(-fsanitize=address)
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fsanitize=address -lasan")
endif()

if("${SANITIZE}" STREQUAL "memory")
  message(STATUS "enabling memory sanitizer")
  add_compile_options(-fsanitize=memory)
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fsanitize=memory")
endif()

if("${SANITIZE}" STREQUAL "thread")
  message(STATUS "enabling thread sanitizer")
  add_compile_options(-fsanitize=thread)
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -fsanitize=thread")
endif()
